### ISSUE TITLE
save file functionality does not work for Firefox Quantum

### ISSUE THREAD

**Issue by lauripiisang** [elfrog/apib-editor#6]
Firefox 58.0 macOs high sierra
Tried with my own apib and the examples.
I have ublock origin installed, but disabled for the page.

Tried using local build and github.io version. 

Tried using Ctrl+S shortcut as well as the icon.

Works like a charm in Safari.

**Comment by elfrog** [comment]
Thank you for your report!
I found that Firefox needs <a> element be appended to the document body to programmatically download a file. I fixed the code and it will work well.
